### ISSUE TITLE
Endpoints for login, signup, displaying and editing user info

### ISSUE THREAD

**Issue by NBNARADHYA** [Cyber-Labs/online-judge#1]
![Welcome Page-signup_v2](https://user-images.githubusercontent.com/45630095/62426564-e538ca80-b703-11e9-98d1-c08e1711834f.png)
![Welcome Page-Login_v2](https://user-images.githubusercontent.com/45630095/62426567-eec23280-b703-11e9-8624-ff9c6c18bd50.png)
![1 Profile-edit](https://user-images.githubusercontent.com/45630095/62426574-1ca77700-b704-11e9-9851-c9c0b7576121.png)
![1 Profile-image upload box](https://user-images.githubusercontent.com/45630095/62426575-1f09d100-b704-11e9-9d52-78fb9e1634b6.png)
![1 Profile-show notification](https://user-images.githubusercontent.com/45630095/62426577-2204c180-b704-11e9-8df4-54dafc7f0d6b.png)

- Create `POST /login` endpoint to login users. The api responds with jwt which can be used for other operations

- Create `POST /signup` endpoint to register the users. The api responds with jwt which can be used for other operations

- Create `GET /users/:{username}` endpoint to display user info

- Create `POST /users/:{username}/update_user` endpoint to update user info

- Create `POST users/:{username}/forgot_password` endpoint to send the password to the registered email

- Create `POST users/:{username}/update_password` endpoint to update the password of the user

**Comment by NBNARADHYA** [comment]
#2

**Comment by nveenjain** [comment]
Please describe the issue.
What you plan to achieve and also post the relevant wireframe if possible.

**Comment by NBNARADHYA** [comment]
Yes..I'm working on it...I'm still not done
