### ISSUE TITLE
API contest client

### ISSUE THREAD

**Issue by NamanZelawat** [Cyber-Labs/online-judge#4]
An application program interface used to retrieve and post data to the database related to the contests from the past, present, future, and solutions for questions related to a contest.

**Comment by NamanZelawat** [comment]
![Question-contest](https://user-images.githubusercontent.com/44704257/62468416-a7937a80-b7b3-11e9-9a0b-898c38d9751e.png)

**Comment by nveenjain** [comment]
Describe the endpoint, how you will approach the problem in this issue itself.
